#!/usr/bin/env node
// Check the French translations against the extracted English dictionaries
// and build the DeepSeek Harness language-pack plugin.
//
//   node scripts/build.mjs [en-dicts.json]
//
// Checks: every English key has a French value, no unknown keys, identical
// {placeholders}. French typography: a non-breaking space is inserted before
// : ; ? ! and inside « » (never inside {placeholders}).
// Output: dist/ (package.json, index.js, client.js, cordis.patch.yml).
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const enPath = process.argv[2] ?? join(ROOT, "source", "en-dicts.json");
const en = JSON.parse(readFileSync(enPath, "utf8"));

const fr = {};
for (const file of readdirSync(join(ROOT, "fr")).filter((f) => f.endsWith(".json")).sort()) {
  const part = JSON.parse(readFileSync(join(ROOT, "fr", file), "utf8"));
  for (const [ns, dict] of Object.entries(part)) fr[ns] = { ...(fr[ns] ?? {}), ...dict };
}

const placeholders = (s) => [...s.matchAll(/\{[^{}]*\}/g)].map((m) => m[0]).sort().join(" ");
const NBSP = " ";
function typography(s) {
  // Protect placeholders, then add non-breaking spaces the French way.
  const saved = [];
  let out = s.replace(/\{[^{}]*\}/g, (m) => `\u0000${saved.push(m) - 1}\u0000`);
  out = out.replace(/ ([:;?!»])/g, `${NBSP}$1`).replace(/« /g, `«${NBSP}`);
  return out.replace(/\u0000(\d+)\u0000/g, (_, i) => saved[Number(i)]);
}

const missing = [];
const problems = [];
for (const [ns, dict] of Object.entries(en)) {
  for (const [key, value] of Object.entries(dict)) {
    const translated = fr[ns]?.[key];
    if (translated === undefined) {
      missing.push(`${ns}:${key}`);
      continue;
    }
    if (typeof translated !== "string") problems.push(`${ns}:${key} is not a string`);
    else if (placeholders(translated) !== placeholders(value)) problems.push(`${ns}:${key} placeholders ${placeholders(translated)} != ${placeholders(value)}`);
  }
}
for (const [ns, dict] of Object.entries(fr)) {
  for (const key of Object.keys(dict)) if (!(key in (en[ns] ?? {}))) problems.push(`${ns}:${key} does not exist in English`);
}

const total = Object.values(en).reduce((n, d) => n + Object.keys(d).length, 0);
const missingNs = [...new Set(missing.map((m) => m.split(":")[0]))];
console.log(`${total - missing.length}/${total} strings translated; ${problems.length} problem(s)`);
if (missingNs.length) console.log(`untranslated namespaces: ${missingNs.join(", ")}`);
for (const p of problems) console.error(`problem: ${p}`);
if (process.argv.includes("--check") || missing.length || problems.length) process.exit(missing.length || problems.length ? 1 : 0);

// ---- build the plugin
const dictionaries = {};
for (const [ns, dict] of Object.entries(en)) {
  dictionaries[ns] = Object.fromEntries(Object.keys(dict).map((k) => [k, typography(fr[ns][k])]));
}
const pkg = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
const dist = join(ROOT, "dist");
mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, "package.json"), `${JSON.stringify({
  name: pkg.name,
  version: pkg.version,
  description: pkg.description,
  license: pkg.license,
  private: true,
  type: "module",
  exports: { ".": "./index.js", "./client": "./client.js", "./package.json": "./package.json" },
  dsh: {
    bundle: { patch: "./cordis.patch.yml" },
    client: { platform: "web", immediately: true, inject: ["@deepseek-ai/dsh-client-locale"] },
  },
}, null, 2)}\n`);
writeFileSync(join(dist, "index.js"), "/** Host half of the French language pack; the Client module does the work. */\nexport function apply() {}\n");
writeFileSync(join(dist, "cordis.patch.yml"), `- insert:\n    - id: locale-fr\n      name: '${pkg.name}'\n`);
writeFileSync(join(dist, "client.js"), `// French language pack for the DeepSeek Harness web UI (generated by scripts/build.mjs).
window.__ModuleLoader__.load({
  id: ${JSON.stringify(pkg.name)},
  factory() {
    const DICTIONARIES = ${JSON.stringify(dictionaries)};
    return {
      inject: ['locale'],
      apply(ctx) {
        ctx.effect(() => ctx.locale.addLanguage({ id: 'fr', label: 'Français', fallback: 'en' }), 'locale-fr: language');
        for (const ns of Object.keys(DICTIONARIES)) {
          ctx.effect(() => ctx.locale.register(ns, 'fr', DICTIONARIES[ns]), 'locale-fr: ' + ns);
        }
      },
    };
  },
});
`);
console.log(`built ${dist} (${Object.keys(dictionaries).length} namespaces)`);
if (!existsSync(enPath)) process.exit(1);
